language: php

php:
  - 7.2.4

before_script:
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
script:
  - vendor/bin/phpunit